# Generated by Django 4.0.4 on 2022-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierwsza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(1, 'Letnie'), (2, 'zimowe'), (3, 'uniwersalne')])),
            ],
        ),
    ]
